import 'package:intl/intl.dart';
import 'package:xml/xml.dart' as xml;
import 'package:hive/hive.dart';

part 'prayer_of_the_day.g.dart'; // This will be generated by the Hive generator.

@HiveType(typeId: 1)
class PrayerOfTheDay {
  @HiveField(0)
  final String title;

  @HiveField(1)
  final String link;

  @HiveField(2)
  final String description;

  @HiveField(3)
  final DateTime publishDate;

  PrayerOfTheDay({
    required this.title,
    required this.link,
    required this.description,
    required this.publishDate,
  });

  factory PrayerOfTheDay.fromXml(xml.XmlElement element) {
    String title = element.findElements('title').first.text;
    String link = element.findElements('link').first.text;
    String description = element.findElements('description').first.text;

    // Extract publish date
    String pubDateStr = element.findElements('pubDate').first.text;
    DateTime publishDate = DateFormat("yyyy-MM-dd HH:mm:ss").parse(pubDateStr);

    return PrayerOfTheDay(
      title: title,
      link: link,
      description: description,
      publishDate: publishDate,
    );
  }

  String get formattedDate {
    return DateFormat('MMMM d, yyyy').format(publishDate);
  }
}
