// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDenDIXpPAr94AAdQ5DLe-s6kaXPJoBI_U',
    appId: '1:487170343472:web:dc683032afe5c92bed63f5',
    messagingSenderId: '487170343472',
    projectId: 'catholicpal-1c81c',
    authDomain: 'catholicpal-1c81c.firebaseapp.com',
    storageBucket: 'catholicpal-1c81c.appspot.com',
    measurementId: 'G-KBVJ7R0WZZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfc13PNMFFMelEyDbGsHoZEF0k5u55g_o',
    appId: '1:487170343472:android:e921a9fc7e38cde6ed63f5',
    messagingSenderId: '487170343472',
    projectId: 'catholicpal-1c81c',
    storageBucket: 'catholicpal-1c81c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_wOb5ZqPMxOEuz9MqNv9u-CCLmG5u1_Y',
    appId: '1:487170343472:ios:e68e1b116f8b9532ed63f5',
    messagingSenderId: '487170343472',
    projectId: 'catholicpal-1c81c',
    storageBucket: 'catholicpal-1c81c.appspot.com',
    iosBundleId: 'com.example.catholicpal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_wOb5ZqPMxOEuz9MqNv9u-CCLmG5u1_Y',
    appId: '1:487170343472:ios:e68e1b116f8b9532ed63f5',
    messagingSenderId: '487170343472',
    projectId: 'catholicpal-1c81c',
    storageBucket: 'catholicpal-1c81c.appspot.com',
    iosBundleId: 'com.example.catholicpal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDenDIXpPAr94AAdQ5DLe-s6kaXPJoBI_U',
    appId: '1:487170343472:web:0687d25d7edceeb8ed63f5',
    messagingSenderId: '487170343472',
    projectId: 'catholicpal-1c81c',
    authDomain: 'catholicpal-1c81c.firebaseapp.com',
    storageBucket: 'catholicpal-1c81c.appspot.com',
    measurementId: 'G-00F88RWVH9',
  );
}
